<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[TestA]]>
    </line>
    <line>
      <![CDATA[testA is 1]]>
    </line>
    <line>
      <![CDATA[TestB]]>
    </line>
    <line>
      <![CDATA[testB is 2]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="79" started-at="2018-03-09T03:13:15Z" finished-at="2018-03-09T03:13:15Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="79" started-at="2018-03-09T03:13:15Z" finished-at="2018-03-09T03:13:15Z">
      <class name="script.Demo">
        <test-method status="PASS" signature="testA()[pri:0, instance:script.Demo@5c3bd550]" name="testA" duration-ms="21" started-at="2018-03-09T08:43:15Z" finished-at="2018-03-09T08:43:15Z">
          <reporter-output>
            <line>
              <![CDATA[TestA]]>
            </line>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method status="PASS" signature="closeApp(org.testng.ITestResult)[pri:0, instance:script.Demo@5c3bd550]" name="closeApp" is-config="true" duration-ms="2" started-at="2018-03-09T08:43:15Z" finished-at="2018-03-09T08:43:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testA status=SUCCESS method=Demo.testA()[pri:0, instance:script.Demo@5c3bd550] output=TestA]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[testA is 1]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApp -->
        <test-method status="FAIL" signature="testB()[pri:0, instance:script.Demo@5c3bd550]" name="testB" duration-ms="4" started-at="2018-03-09T08:43:15Z" finished-at="2018-03-09T08:43:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: nullat org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.fail(Assert.java:103)at script.Demo.testB(Demo.java:29)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[TestB]]>
            </line>
          </reporter-output>
        </test-method> <!-- testB -->
        <test-method status="PASS" signature="closeApp(org.testng.ITestResult)[pri:0, instance:script.Demo@5c3bd550]" name="closeApp" is-config="true" duration-ms="1" started-at="2018-03-09T08:43:15Z" finished-at="2018-03-09T08:43:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testB status=FAILURE method=Demo.testB()[pri:0, instance:script.Demo@5c3bd550] output=TestB]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[testB is 2]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- script.Demo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
